version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule: {interval: monthly}
    reviewers: [daveshow]
    assignees: [daveshow]

  - package-ecosystem: docker
    directory: /
    schedule: {interval: monthly}
    reviewers: [daveshow]
    assignees: [daveshow]